name: "Podcast Generator"
author: "Montasir Rahman"
description: "Generates a Feed for a Podcast"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-branch"
  color: "red"

inputs:
  email:
    description: "The commiter's email address"
    required: true
    default: ${{ github.actor }}@localhost

  name:
    description: "The Commiter's name"
    default: true
    default: ${{ github.actor }}