name: "Podcast Generator"
author: "Montasir Rahman"
description: "Generates a Feed for a Podcast"

inputs:
  email:
    description: "The committer's email address"
    required: true
  name:
    description: "The committer's name"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_EMAIL: ${{ inputs.email }}
    INPUT_NAME: ${{ inputs.name }}

branding:
  icon: "git-branch"
  color: "red"